application: gae-exercise
version: develop
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: routes.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
